version: '3.1'

services:

  mongo1:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: evitcaer
        MONGO_INITDB_ROOT_PASSWORD: johnjones
        MONGO_INITDB_DATABASE: socialchat

  mongo2:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: evitcaer
      MONGO_INITDB_ROOT_PASSWORD: johnjones
      MONGO_INITDB_DATABASE: socialchat

  mongo3:
    image: mongo
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: evitcaer
      MONGO_INITDB_ROOT_PASSWORD: johnjones
      MONGO_INITDB_DATABASE: socialchat